site_name: Gufo Traceroute
site_description: Gufo Traceroute Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_traceroute/"
copyright: "&copy; 2022-25, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_traceroute/
repo_name: gufolabs/gufo_traceroute
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference: reference.md
  - Examples:
      - Overview: examples/index.md
      - Traceroute: examples/traceroute.md
  - Developers' Guide:
      - Overview: dev/index.md
      - Developer's Environment: dev/environment.md
      - Building and Testing: dev/testing.md
      - Common Tasks: dev/common.md
      - Code Quality: dev/codequality.md
      - Code Base: dev/codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Supported Standards: dev/standards.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-GW3X378HNJ
